[package]
name = "repe"
version = "0.1.2"
edition = "2021"
description = "Rust implementation of the REPE RPC protocol (JSON-focused)"
license = "MIT"
repository = "https://github.com/repe-org/repe-rs"
documentation = "https://crates.io/crates/repe"
readme = "README.md"
keywords = ["rpc", "protocol", "repe", "json"]
categories = ["network-programming", "encoding"]
include = [
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "src/**",
    "examples/**",
    "tests/**",
]
exclude = ["Cargo.toml.orig"]

[dependencies]
serde = { version = "1", features = ["derive" ] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time", "io-util"] }

[dev-dependencies]
rand = "0.8"
