[package]
name = "repe"
version = "0.2.0"
edition = "2021"
description = "Rust implementation of the REPE RPC protocol (JSON-focused)"
license = "MIT"
repository = "https://github.com/repe-org/repe-rs"
documentation = "https://crates.io/crates/repe"
readme = "README.md"
keywords = ["rpc", "protocol", "repe", "json"]
categories = ["network-programming", "encoding"]
include = [
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "src/**",
    "examples/**",
    "tests/**",
]
exclude = ["Cargo.toml.orig"]

[features]
default = []
parking-lot = ["dep:parking_lot"]

[dependencies]
beve = "0.1"
serde = { version = "1", features = ["derive" ] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time", "io-util", "sync"] }
repe-derive = { path = "repe-derive" }
parking_lot = { version = "0.12", optional = true }

[dev-dependencies]
rand = "0.8"
