[package]
name = "repe-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Procedural macros for the repe crate"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro-crate = "1"
